services:
  - type: web
    name: karate-app-backend
    runtime: python
    rootDir: backend/api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 2 app:APP
    envVars:
      - key: LOCATIONIQ_API_KEY
        sync: false
      - key: KARATEAPP_BACKEND_DATABASE
        value: /var/data/geocode_cache.sqlite3
    disk:
      name: backend-cache
      mountPath: /var/data
      sizeGB: 1
